import {
  BookOpen,
  Dumbbell,
  Briefcase,
  Brain,
  Book,
  Code,
  Music,
  Palette,
  Camera,
  Gamepad2,
  Utensils,
  Home,
  Heart,
  Star,
  Zap,
  Target,
  Trophy,
  Flame,
  Lightbulb,
  PenTool,
  Mic,
  Guitar,
  Bike,
  PersonStanding,
  Waves,
  Mountain,
  TreePine,
  Coffee,
  Smartphone,
  Monitor,
  Headphones,
  Film,
  Tv,
  ShoppingBag,
  Wallet,
  GraduationCap,
  Languages,
  Calculator,
  FlaskConical,
  Microscope,
  Stethoscope,
  Pill,
  Salad,
  type LucideIcon,
} from 'lucide-react';

// Mapa de ícones disponíveis para atividades
export const ACTIVITY_ICONS: Record<string, LucideIcon> = {
  BookOpen,
  Dumbbell,
  Briefcase,
  Brain,
  Book,
  Code,
  Music,
  Palette,
  Camera,
  Gamepad2,
  Utensils,
  Home,
  Heart,
  Star,
  Zap,
  Target,
  Trophy,
  Flame,
  Lightbulb,
  PenTool,
  Mic,
  Guitar,
  Bike,
  PersonStanding,
  Waves,
  Mountain,
  TreePine,
  Coffee,
  Smartphone,
  Monitor,
  Headphones,
  Film,
  Tv,
  ShoppingBag,
  Wallet,
  GraduationCap,
  Languages,
  Calculator,
  FlaskConical,
  Microscope,
  Stethoscope,
  Pill,
  Salad,
};

// Lista de nomes de ícones para seleção
export const ACTIVITY_ICON_NAMES = Object.keys(ACTIVITY_ICONS);

// Nomes amigáveis para exibição
export const ACTIVITY_ICON_LABELS: Record<string, string> = {
  BookOpen: 'Livro',
  Dumbbell: 'Haltere',
  Briefcase: 'Trabalho',
  Brain: 'Cérebro',
  Book: 'Livro Fechado',
  Code: 'Código',
  Music: 'Música',
  Palette: 'Arte',
  Camera: 'Câmera',
  Gamepad2: 'Games',
  Utensils: 'Cozinha',
  Home: 'Casa',
  Heart: 'Coração',
  Star: 'Estrela',
  Zap: 'Raio',
  Target: 'Alvo',
  Trophy: 'Troféu',
  Flame: 'Chama',
  Lightbulb: 'Lâmpada',
  PenTool: 'Caneta',
  Mic: 'Microfone',
  Guitar: 'Guitarra',
  Bike: 'Bicicleta',
  PersonStanding: 'Corrida',
  Waves: 'Ondas',
  Mountain: 'Montanha',
  TreePine: 'Natureza',
  Coffee: 'Café',
  Smartphone: 'Celular',
  Monitor: 'Monitor',
  Headphones: 'Fones',
  Film: 'Filme',
  Tv: 'TV',
  ShoppingBag: 'Compras',
  Wallet: 'Finanças',
  GraduationCap: 'Graduação',
  Languages: 'Idiomas',
  Calculator: 'Calculadora',
  FlaskConical: 'Ciência',
  Microscope: 'Microscópio',
  Stethoscope: 'Saúde',
  Pill: 'Medicamento',
  Salad: 'Alimentação',
};

interface ActivityIconProps {
  icon: string;
  size?: number;
  className?: string;
}

export function ActivityIcon({ icon, size = 20, className }: ActivityIconProps) {
  const IconComponent = ACTIVITY_ICONS[icon];

  if (IconComponent) {
    return <IconComponent size={size} className={className} />;
  }

  // Fallback para emoji se não encontrar o ícone
  return <span className={className} style={{ fontSize: size * 0.8 }}>{icon}</span>;
}
